Change the provider to support TF SDK v2
terraform-redhat/terraform-provider-rhcs pull request #262
Opened 2023-09-07 10:04 UTC by bardielle

2023-09-07 11:23 UTC, osherdp requested changes

2023-09-07 11:23 UTC, osherdp commented on build/ci-tf-e2e.Dockerfile
> +    cd terraform-cprovider-rhcs && go mod tidy && go mod vendor && make install &&\
cprovider?

2023-09-07 11:23 UTC, osherdp commented on internal/rhcs/cloudprovider/cloud_providers_state.go
> +			Description: "Unique identifier of the cloud clusterservice. This is what " +
this seems like a really weird replace-all. it should be 
```suggestion
			Description: "Unique identifier of the cloud provider. This is what " +
```

2023-09-07 11:23 UTC, osherdp commented on ci/apply_folder.sh
> +# Check for clusterservice source and version 'provider_source = "hashicorp/rhcs" (or "terraform.local/local/rhcs"') and 'provider_version = ">=1.0.1"'
looks like a bad string replacement

2023-09-07 11:59 UTC, osherdp commented on build/ci-tf-e2e.Dockerfile
> +    cd terraform-cprovider-rhcs && go mod tidy && go mod vendor && make install &&\
handled via https://github.com/terraform-redhat/terraform-provider-rhcs/pull/263

2023-09-07 11:59 UTC, osherdp commented on ci/apply_folder.sh
> +# Check for clusterservice source and version 'provider_source = "hashicorp/rhcs" (or "terraform.local/local/rhcs"') and 'provider_version = ">=1.0.1"'
handled via https://github.com/terraform-redhat/terraform-provider-rhcs/pull/263

2023-09-07 12:00 UTC, osherdp commented on internal/rhcs/cloudprovider/cloud_providers_state.go
> +			Description: "Unique identifier of the cloud clusterservice. This is what " +
handled via https://github.com/terraform-redhat/terraform-provider-rhcs/pull/263

2023-09-07 12:34 UTC, amalykhi commented
/retest

2023-09-07 12:56 UTC, amalykhi commented
ooo. I think the CI fails because of your changes. 
CI changes PR will fail because it would miss your PR)

2023-09-12 06:53 UTC, nirarg commented
Closing This PR, because moving to latest framework

2023-09-12 06:53 UTC, closed without merging